
name: Build K2P-openwrt

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install  build-essential asciidoc binutils bzip2 gawk gettext git \
        libncurses5-dev libz-dev patch python3.5 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 \
        subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev \
        texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool \
        autopoint device-tree-compiler g++-multilib antlr3 gperf
    - name: Clone source code
      run: |
        git clone -b dev-19.07 https://github.com/Lienol/openwrt /opt/op19
        cd /opt/op19
        ./scripts/feeds clean
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make menuconfig
        make -j8 download V=s
    - name: Build Firmware
      env:
        TNAME: k2p-openwrt
      run: |
    
        make -j8 V=s
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/op19
